# -------------------------------------------------------------------
# Backlift config.yml file. These settings control various javascript
# and css compilers, file directory listings, data prefetching, 
# optimization, oauth keys, and other server functions
# -------------------------------------------------------------------


# autoroute: the automatic routing feature is useful for single-page 
# websites that implement their own javascript routing. If autoroute
# is set to 'yes', all requests to URLs that don't match a file or API 
# endpoint will be routed to the index.html file.

autoroute: yes

# development: determine if page should show Backlift admin tab on
# bottom right corner. If 'yes', then tab is show, 'no' hides it.

development: yes

# facebook_secret: secret key for each Facebook app. You can find it from
# Facebook on app's settigns page with name "App Secret".

facebook_secret: 'fillme'

# collections: defines validation rules for Backlift data API.
# There are various different rules. See complete reference from
# https://www.backlift.com/docs/guides/validation.html
collections:
    submissions:
        firstname: {required: yes}
        lastname: {required: yes}
        email: {type: email, required: yes}
        favoritecolor: {required: yes}

